version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "crime-applications-dev"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1wpe1m2q8vbbi"
s3_prefix = "crime-applications-dev"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Stage=\"dev\""
image_repositories = []
