on:
  push:
    branches:
      - main
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: aws-actions/setup-sam@v1
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: eu-west-2
      # sam build
      - run: sam build --use-container

      # lambda code versions
      - run: ./.github/scripts/lambda-versions.sh
        id: lambda-versions

      # run Unit tests - specify unit tests here

      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name crime-applications-staging --s3-bucket crime-apply-api-dynamo-lambda --s3-prefix sam --capabilities CAPABILITY_IAM --parameter-overrides Stage=staging ReadVersion=${{ steps.lambda-versions.outputs.read }} WriteVersion=${{ steps.lambda-versions.outputs.write }}
